### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by rayshen3** [mitchellrj/python-pgp#13]
```
pip install py-pgp
Downloading/unpacking py-pgp
  Downloading py-pgp-0.0.1.tar.gz (126kB): 126kB downloaded
  Running setup.py (path:/tmp/pip_build_ray/py-pgp/setup.py) egg_info for package py-pgp
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_ray/py-pgp/setup.py", line 30, in <module>
        'CHANGELOG.rst',
    IOError: [Errno 2] No such file or directory: 'LICENSE.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_ray/py-pgp/setup.py", line 30, in <module>

    'CHANGELOG.rst',

IOError: [Errno 2] No such file or directory: 'LICENSE.rst'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_ray/py-pgp
Storing debug log for failure in /home/ray/.pip/pip.log
```

```
ray@um:~/py-pgp-0.0.1$ sudo python setup.py
Traceback (most recent call last):
  File "setup.py", line 30, in <module>
    'CHANGELOG.rst',
IOError: [Errno 2] No such file or directory: 'LICENSE.rst'
```
when i install py-pgp module with pip or source code, got errors like that,
is there someone can help me :(

ubuntu 14:04
pip 9.0.1
[pip list](https://gist.github.com/rayshen3/42658349444833be9ad83435678c2e9d)

**Comment by DrewQuartic** [comment]
Getting the same error. Did you ever resolve it?
